services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
    public: true

  cache.redis_connection:
    class: Redis
    factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
    arguments:
      - '%env(REDIS_DSN)%'

  app.redis_adapter:
    class: Symfony\Component\Cache\Adapter\RedisAdapter
    arguments:
      - '@cache.redis_connection'
      - 'app'
      - 0

  App\Service\MetricsClient:
    arguments:
      $url: '%env(INFLUX_URL)%'
      $token: '%env(INFLUX_TOKEN)%'
      $org: '%env(INFLUX_ORG)%'
      $bucket: '%env(INFLUX_BUCKET)%'

  App\Service\SwopExchangeRateProvider:
    arguments:
      $clientApi: '@App\Service\ExchangeRateClientInterface'
      $cache: '@app.redis_adapter'
      $ttlSeconds: '%env(int:RATES_TTL_SECONDS)%'

  App\Service\ConversionService:
    arguments:
      $rates: '@App\Service\ExchangeRateProviderInterface'
      $calculator: '@App\Service\MoneyConversionCalculator'
      $metrics: '@App\Service\MetricsClient'
      $validator: '@validator'

  App\Service\ExchangeRateProviderInterface: '@App\Service\SwopExchangeRateProvider'

  App\Service\ExchangeRateClientInterface: '@App\Service\SwopApiClient'

  App\Service\SwopApiClient:
    arguments:
      $baseUrl: '%env(SWOP_API_BASE)%'
      $apiKey: '%env(SWOP_API_KEY)%'
      $timeoutSeconds: 3.0
