app = "currency-converter-service"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[env]
APP_ENV = "prod"
APP_DEBUG = "0"
APP_SECRET = "ChangeThisSecret"

SWOP_API_BASE = "https://swop.cx/rest"

RATES_TTL_SECONDS = "3600"

INFLUX_URL = ""
INFLUX_TOKEN = ""
INFLUX_ORG = ""
INFLUX_BUCKET = ""

[[services]]
protocol = "tcp"
internal_port = 80

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
soft_limit = 50
hard_limit = 100
