framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false

  router:
    utf8: true

  csrf_protection: true

  http_client:
    default_options:
      timeout: 3.0

  validation:
    enable_attributes: true

  cache:
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_URL)%'

  session:
    handler_id: null
    save_path: '%env(REDIS_URL)%'
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
